label chap4:
    call titlepage(4)
    scene garden with dissolve 
    x "Colchiques dans les prés ! Fleurissent, fleurissent. Colchiques dans les prés ! C'est la fin de l'été."
    "Un chat chantonne tout en arrosant joyeusement de magnifiques fleurs."
    blanche "C’est… C’est si joli ! Ça brille de partout ! C’est si vert !"
    x "Ho, ho, il en faut peu pour être heureux, vraiment très peu pour être heureux."
    x "Émeraude est satisfait du nécessaire !"
    emeraude "Un peu d'eau fraîche et de verdure !"
    "Le chat tournoie sur lui-même, faisant répandre l’eau autour de lui."
    emeraude "Que nous prodigue la nature. Quelques rayons de miel et de soleil."
    blanche "Haha, tu es marrant, Émeraude !"
    blanche "Moi, je m’appelle Blanche !"
    emeraude "Blanche ! Vas-y secoue-toi et danse ! "
    blanche "Oh non, je suis désolé. Je viens pour autre chose…"
    emeraude "Dis-moi, c’est quoi ton problèèème ?"
    blanche "Je viens pour récupérer la boule Vert… C’est pour mon papa…"
    emeraude "Ça ne tient pas à toi ! Ça ne tient pas à moi !"
    emeraude "Quand Madame Arc-en-Ciel nous dit ce que l'on peut être !"
    emeraude "Moi, je m’appelle Émeraude, gardien de Couleurs."
    emeraude "Boule de Cristal, du pareil au même."
    emeraude "Moi, je m’appelle Émeraude, gardien de Couleurs."
    emeraude "Quand je rêve de Madame Arc-en-Ciel, c'est Émeraude qui saigne."
    blanche "J’ai l’impression que tout ce que tu dis, ce sont des paroles de différentes chansons."
    emeraude "C'est pas ma faute, et quand je donne ma langue au chat, je vois les autres…"
    emeraude "Tout prêts à se jeter sur moi… C'est pas ma faute à moi !"
    blanche "Arf… Cela va être difficile de communiquer…"
    blanche "Réfléchissons..."
    blanche "Ah ! Je sais déjà que tu as un contrat avec Madame Arc-en-Ciel pour garder ta boule de cristal."
    blanche "Mais, s’il te plaît, juste pour une nuit, pour mon papa. C’est ma mission."
    emeraude "Ma mission n'a qu'une seule façon ! De tourner le monde ! De le changer !"
    blanche "S’il te plaît, aide-moi !"
    blanche "Mon papa a aussi une mission de la part de Madame Arc-en-Ciel !"
    blanche "Il m’a dit qu’il est très important comme Madame Arc-en-Ciel !"
    blanche "Mais il est malade, alors il ne peut rien faire…."
    blanche "C’est pour ça que je veux lui remonter le moral ! Une dernière fois…"
    emeraude "Non, non, non, non ! Je ne peux pas m'en passer ! Non, non, non, non !"
    blanche "Zut, comment je peux convaincre Émeraude…"

    menu:
        "Tirer une de ses oreilles et lui crier de dessus d’arrêter de chanter":
            blanche "Arrête de chanter et écoute-moi !!!"
            emeraude "Est-ce que tu m’entends ? Hé ho !"
            blanche "ARRÊTE DE CHANTER !"
            blanche "Il faut que je récupère cette boule de cristal rapidement !"
            blanche "Je n’ai pas le temps de discuter avec toi !"
            emeraude "J’ai pas le teeemps !!! Mon espriiiiiit glisse ailleurs !"
            blanche "S’il te plaît…"
            "Je commence à pleurer."
            emeraude "..."
        "Faire les yeux du Chat Potté (encore)":
            "Cela a marché avec Violet, peut-être que ça marchera aussi avec Émeraude."
            "Je lui fais les yeux du Chat Potté"
            emeraude "Blanche a les yeux revolver. Blanche a le regard qui tue. Blanche a tiré en premier."
            emeraude "M’a touché, c’est foutu."
        "Demander en chantant":
            blanche "Comment puis-je oublier ce coin de paradis ?"
            blanche "Ce petit bout de terre où vit encore mon père ?"
            blanche "Comment pourrais-je faire pour récupérer la boule de cristal ?"
            blanche "Et qu’on… Hmpf. AÏÏÏeeeuhhh."
            "J’ai mordu ma langue."
            emeraude "Ho ho. Je… Je t’aime comme une chanson d’amour, baby. Ho ho."

    emeraude "À l’aide ! J’ai besoin de quelqu’un ! À l’aide ! Pas n’importe qui ! À l’aide ! Tu sais, j'ai besoin de Blanche ! "
    blanche "Que ? Quoi ?! Qu’est-ce qui se passe ?!"
    emeraude "Je troque ma boule de cristal contre une aide."
    emeraude "J'échangerai ma vie à moi, confortable et sans lacune."
    emeraude "Il existe un memory virtuel et différent."
    emeraude "Où chaque seconde fait de nous des combattants."
    emeraude "Notre seul espoir est de tout réassocier..."
    blanche "Un memory…"
    blanche "Bon, on y va et on saura ce que je dois faire."

    # TODO: Afficher le mini-jeu de memory
    # si echec (time out) : 
    # emeraude "Oh non ! Encore une fois !"
    #     loop
    # si réussi
    # emeraude "Yeah ! Bravo ! Oui, viens danser ! Oui, c’est la vie, la la la la la !"

    emeraude "Voilà, voilà, voilà, voilà la boule de cristal."
    emeraude "Et si mon heure sonne, oh oh. Pleure pas rigole, oh oh. On m'appelle l’Émeraude."
    blanche "Merci ! Merci Émeraude ! Tu me sauves !"
    blanche "Zut, il ne me reste plus beaucoup de temps."
    blanche "Il faut que je me dépêche."
    emeraude "Libérée, délivrée, je n’ai plus de boules à m’occuper, libérée, délivrée, c’est décidé, c’est fini !"
    emeraude "J’ai laissé mon contrat en été, perdu avec Blanche !"
    emeraude "La boule verte est pour moi le prix de la liberté !" 
    "Quelques minutes plus tard…"
    emeraude "Poum, poum, poum, poum !"
    grosso "Émeraude !"
    grosso "Dis-moi as-tu vu un enfant de cette taille ?"
    emeraude "Je ne sais pas."
    emeraude "Comment te dire ?"
    emeraude "J’aurai peur de tout foutre en l’air !"
    grosso "Ah oui…"
    grosso "C’est vrai qu’il faut chanter…"
    grosso "C’est oui ou bien c’est non ?"
    maigrichon "Ah !"
    maigrichon "La boule Vert n’est plus là !"
    grosso "Encore une de perdue ?!"
    grosso "Aaah… Où est-ce que cet enfant a-t-il bien pu aller ?"
    "Emeraude les voit s’en aller."
    emeraude "Minuit se lève, en haut des tours, les voix se taisent et tout devient aveugle et sourd, la nuit camoufle, pour quelques heures, la zone Blanche de ces nuisibles visiteurs !"

