label chap3:
    call titlepage(3)
    scene forest with dissolve 
    "Le présentateur Cyan est très connu du grand public pour son émission Jean Racine et des Saules."
    "Il va, avec ses équipes, à travers les forêts du monde présenter aux autres chats les beautés de la nature."
    cyan "Bonjour à toutes et tous !"
    cyan "Bienvenue dans Jean Racine et des Saules, l'émission d'Art et Culture la plus connue de Monde 2 ! "
    blanche "Bonjour, désolé de te déranger, je voudrais savoir…"
    cameraman "Chuuuuuuuuuut !"
    cyan "Nous voici donc dans la forêt Arc-En-Ciel, très connue pour sa rivière, mais surtout pour ses truites."
    cyan "Admirez donc ces magnifiques chênes centenaires, ces hêtres majestueux et ces petits sapins."
    cyan "Tous sont le fruit d'une collaboration entre l'être humain et la nature. Observons maintenant les truites."
    cameraman "Je suis désolé chaton, mais nous n'avons pas réussi à trouver de truites arc-en-ciel dans la rivière, nous avons seulement quelques truites fario."
    cameraman "Un simple amateur de poisson verra la différence. Je coupe la bande vidéo le temps de trouver une solution."
    cyan "Mais c'est horrible, qu'allons-nous dire à nos téléspectateurs ?!"
    cyan "Nous ne pouvons pas les décevoir."
    cyan "Présenter la forêt Arc-En-Ciel sans ses truites, c'est comme présenter des crêpes sans oeufs."
    cyan "C'est impensable ! Inimaginable !"
    cameraman "Cela peut prendre plusieurs heures, les truites Arc-En-Ciel se font de plus en plus rares dans la rivière depuis les sécheresses de 2022 et la pêche intensive de truites."
    blanche "Excuse-moi, j'ai une question à te poser."
    cameraman "Ça suffit comme ça, on est en plein tournage, ouste !"

    menu:
        "Le traiter de rustre":
            blanche "Espèce de rustre, t'es trop méchant avec les enfants, je boude."
            cameraman "C'est pas ce que j'ai voulu dire, mais tu m'as compris, tu nous gênes petit."
            blanche "Mais pourquoi tu avais besoin d'être aussi méchant qu'est-ce que j'ai fait ?"
            cameraman "Je n'aime pas les enfants c'est tout."
            blanche "Je ne peux vraiment pas essayer de vous aider ?"
        "Tourner les talons":
            cyan "Attends, attends, ne t'en va pas, j'ai tout mon temps de toute façon maintenant, vas-y pose ta question"
            blanche "C'est que c'est un peu compliqué, vous n'allez sans doute pas me comprendre."
        "Lui répondre poliment":
            blanche "Excuse-moi, mais j'ai l'impression que je ne gêne plus tant que ça, poser une simple question ne devrait pas être un problème."
            cameraman "Bon, OK, mais pas longtemps alors"
            blanche "Merci."

    cyan "De quoi s'agit-il ?"
    blanche "Je souhaitais te proposer un marché : je te pêche une truite arc-en-ciel et tu me cèdes ta boule cyan pour une nuit, ça vous va ?"
    cyan "Pourquoi je devrais te croire ?"
    cyan "En plus, je ne suis pas censé me séparer de ma boule, cela fait partie des clauses de mon contrat et Cyanmois ne faillit à rien !"
    blanche "Je suis un expert de la pêche : mon père m'a appris quand j'étais minaud."
    blanche "Mais maintenant, il est très malade et dans son état, il ne peut plus se lever."
    blanche "Il m'a raconté qu'il aimerait voir une dernière fois les couleurs de l'arc-en-ciel."
    blanche "Ce serait pour lui l'ultime cadeau. Celui sur lequel se repose ses dernières forces."
    cyan "Tu ne serais pas l'enfant de Noir ?"
    cyan "C'est une légende vivante en matière de pêche !"
    blanche "Si, bien sûr ! Je ne pensais pas que mon père était si connu !"
    blanche "À la maison, tout est noir ou blanc. Aucun souvenir de couleur ne persiste."
    blanche "Je suppose que c'est pour ça que je n'ai jamais rien su de sa notoriété."
    cyan "Noir était un grand pêcheur, j'avais fait un de mes tout premiers reportages sur la rivière Dark Quidor, une rivière très sombre qui apporte le malheur autour d'elle."
    cyan "À cette époque, ton père espérait attraper le brochet doré, une légende locale."
    cyan "Malheureusement, le malheur est venu auprès de ton père. Son amour de la pêche l'aura aveuglé à jamais."
    cyan "Je me souviens que tous les journaux de l'époque en avaient parlé, c'est une véritable tragédie."
    blanche "Oui, et depuis quelque temps, son état se dégrade."
    blanche "Je n'ai peur qu'il ne décède avant que j'eusse pu réaliser son dernier voeu : voir les sept vraies couleurs de l'arc-en-ciel."
    cyan "Bon, dans ce cas, c'est d'accord."
    cyan "Je n'ai pas trop le choix sinon mon reportage est foutu. Alors si ça peut faire plaisir à Noir, je peux bien te faire ce geste."
    cyan "Tu vois ce lac d'où démarre la rivière, c'est là qu'il y avait plein de truites par le passé."
    cyan "Je te fournis la canne à pêche et je te souhaite bonne chance."
    cyan "J'aimerais reprendre le tournage dans un quart d'heure maximum."
    cyan "Ne traîne pas trop."

    # TODO: Afficher le mini-jeu du lac
    # if all_completed:
    #     blanche "Voilà ta truite arc-en-ciel, ça faisait longtemps que je n'en avais pas pêché d'aussi grosse."
    #     cyan "Mais c'est extraordinaire ! Je ne m'attendais pas à présenter une perle rare dans mon émission ! Tu as bien mérité ta récompense, voici la boule cyan. Je compte sur toi pour me la rendre au plus vite car Mme Arc-En-Ciel ne voit pas toujours d'un très bon oeil ce genre d'arrangement."
    #     blanche "Ne t'inquiète pas, je fais au plus vite, merci encore"

    "Blanche s'en va en courant le longrosso de la rivière."
    "La prise de vue de Cyanmois peut alors reprendre."

    cyan "Voyez donc chers téléspectateurs !"
    cyan "Un admirateur exceptionnel de l'émission nous a donné cette truite Arc-En-Ciel fraîchement pêchée dans la rivière."
    cyan "Un véritable exemple…"
    grosso "Coupe cette caméra, s'il te plaît."
    cameraman "Mais…"
    maigrichon "Ne discute pas. On a quelques mots à vous dire à tous les deux."
    cyan "Je suppose que vous venez de nous voir remettre la boule cyan à cet enfant et que vous désapprouvez cette démarche."
    cyan "Je ne prendrai même pas la peine de vous expliquer, vous ne comprendriez pas."
    cyan "Je sais également ce que je risque et j'en suis tout à fait conscient."
    grosso "Pfff… pathétique."
    grosso "Dis-nous au moins où il est parti, ça nous facilitera la tâche et ça permettra peut-être d'alléger ta peine."
    cyan "N'y comptez pas."
    maigrichon "Je l'ai vu remonter le cours de la rivière de toute façon. Dépêchez-nous !"
    "Grosso et maigrichon partent à sa poursuite à travers les hautes herbes"
    jump chap4
