label end_neutral:
    noir "Urgh… Aaahh !!!"
    "Noir crie de douleur."
    blanche "Papa ! Hmpf… Hmpf…"
    "J'ai couru comme j'ai pu à la maison."
    blanche "Papa ! Tu vas bien ?! Regarde, je t'ai amené les sept boules de cristal !"
    noir "Urgh… [player_name], c'est toi ?"
    blanche "Je voulais te faire une surprise et te montrer l'Arc-en-Ciel ! Comme tu es tout le temps malade, j'ai décidé de t'amener les sept boules de l'Arc-en-Ciel ! Regarde ! Tada !"
    noir "Ah… [player_name], pourquoi as-tu fait ça ? Kof, kof."
    noir "Cela va perturber l'équilibre du royaume. Madame Arc-en-Ciel ne sera pas contente."
    noir "Va remettre ces boules de cristal, là où elles doivent être. Kof, kof."
    blanche "Je voulais seulement te faire une surprise…" 
    noir "On risque d'avoir des ennuis si Madame Arc-en-Ciel découvre que tu as volé ses boules."
    blanche "Mais, regarde Papa ! Ces couleurs sont jolies, non ? Tu… Tu n'aimes pas mon cadeau ?"
    "Je commence à pleurer."
    blanche "J'ai fait tout le royaume pour te montrer l'Arc-en-Ciel. Il fait si noir ici, c'est si triste."
    blanche "Je voulais seulement que tu ailles mieux en voyant ces jolies couleurs !!!"
    blanche "Mais, tu n'y fais pas du tout attention. Madame Arc-en-Ciel, par-ci, Madame Arc-en-Ciel, par là ! Je le sais ! Les gardiens de Couleurs n'ont pas arrêté de me dire que c'était dangereux ce que je faisais !"
    blanche "Pourtant... Poutant, j'ai fait tout ça parce que tu es toujours triste, malade et plein d'idées noires."
    blanche "C'est si mal que ça de vouloir voir les couleurs avec toi ? Je pensais qu'en voyant ces jolies choses, tu irais mieux." 
    noir "Je… C'est très joli, [player_name]."
    noir "Je vais mieux merci…"
    #<illu noir qui prend blanche dans ses bras, une partie de son corps est dans un état de paillettes lumineuses noires (exemple)>
    "Des particules lumineuses noires apparaissent autour de Noire."
    blanche "Tu mens. Tu es en train de disparaître."
    "Je commence à pleurer."
    noir "Viens là…"
    "Papa sourit et utilise ses dernières forces pour se lever et me prendre dans ses bras."
    blanche "Sniff… Sniff…"
    noir "Ne pleure pas..."
    noir "Même si je perds de plus en plus de luminosité et que je ne deviens qu'une simple ombre qui disparaît à la lumière, sache que j'ai eu une vie merveilleuse."
    noir "Je ne regrette pas d'avoir vécu à tes côtés."
    "À ces mots, il prend mes mains, les embrasse et les place au niveau de son coeur."
    blanche "Ton coeur, il bat faiblement…"
    noir "Je n'ai aucun regret [player_name] alors… Souris pour moi. Souris pour toi. Vis ta vie."
    noir "[player_name], profite de ta vie et ne regrette rien."
    noir "Ceci n'est pas un adieu, ceci est juste un au revoir."
    "Papa pointe mon coeur du bout de son doigt."
    noir "Je serai toujours là à tes côtés dans cette petite place au fond de ton coeur."
    blanche "Papa…"
    noir "Prends bien soin de toi, [player_name]."
    blanche "PAPA ! Non, ne me laisse pas !!!" 
    noir "Au revoir [player_name]."
    blanche "PAPA !!!"
    "Le bandeau de Noir tombe, révélant ses yeux arc-en-ciel."
    noir "Merci de m'avoir fait voir l'arc-en-ciel une dernière fois…"
    "C'est ainsi que Noir, mon père, disparut dans l'obscurité…"
    "Quant aux boules de cristal..."
    "Les gardes de Madame Arc-en-Ciel les récupérèrent et me guidèrent vers elle."
    "Par chance, après avoir expliqué ma situation, Madame Arc-en-Ciel me prit dans ses bras et me pardonna pour tout ce que j'avais fait pour mon père..."
