label end_bad:
    grosso "On te tient maintenant ! Rends-nous les boules tout de suite !"
    blanche "Oh non ! Les gardes de Madame Arc-en-Ciel ! Fuyons !"
    "Je cours de toutes mes forces."
    maigrichon "Pas si vite !"
    blanche "Hmpf... Hmpf..."
    blanche "Ah !"
    blanche "Oh non ! Une impasse !"
    maigrichon "Ha ha ! Tu ne peux plus t'échapper maintenant, hein ?"
    maigrichon "Viens là !"
    blanche "Ah ! Aïe !"
    "Le garde m'attrape une main et m'arrache les boules de cristal."
    blanche "Non ! Non ! Pas les boules de cristal !"
    blanche "S'il vous plaît ! C'est pour mon père !"
    grosso "Madame Arc-en-Ciel a bien été formelle à ce sujet."
    grosso "Aucun étranger ne doit s'emparer des boules ! Ce sont les ordres."
    grosso "Maigrichon ! Passe-moi les menottes, on l'embarque !"
    grosso "Finie la rigolade ! Tu vas voir ce qu'il en coûte de s'opposer aux représentants de Madame Arc-en-Ciel !"
    blanche "Ah ! Aïe !"
    "Le garde me menotte les mains."
    blanche "S'il vous plaît ! Je peux tout vous expliquer !"
    grosso "On n'a pas que ça à faire. Tu iras t'expliquer avec les chauves-souris dans ta cellule."
    blanche "S'il vous plaît ! S'il vous plaît !"
    blanche "Pitié, juste cinq minutes ! Il faut que je montre ces boules à mon papa !"
    "Nous passons devant la maison."
    blanche "Oh non, Papa !"
    noir "Kof, kof…"
    "Mon papa tourne la tête au-dehors."
    blanche "Pardon, Papa ! Je m'excuse... Pardon. J'ai fait une grosse bêtise."
    noir "Kof, kof... On dirait qu'il y a de l'agitation dehors..."
    noir "Kof, kof... [player_name] ! Tu peux m'apporter un verre d'eau ? Kof, kof... "
    noir "[player_name] ?"
    noir "[player_name:.2]... [player_name] ?"
    noir "[player_name:.2]..."
    "Tels furent les derniers mots de mon papa avant de se transformer en un nuage de poussière noire..."
    "Quant à moi, j'ai fini dans les geôles du palais Arc-en-Ciel sans jamais avoir pu m'expliquer."
