label end_good:
    blanche "Héhé ! J'ai réussi à avoir les sept boules de cristal ! J'espère que Papa sera content."
    madame "Un instant ! C'est donc toi, le petit enfant qui sème la zizanie dans ce royaume."
    madame "Que fais-tu ? Rends-moi mes boules ! Pourquoi les avoir prises ?!"
    madame "Tu ne sais donc pas que cela perturbe l'équilibre de ce monde ?!"
    blanche "Ah ! Euh…" with vpunch
    blanche "C'est Madame Arc-en-Ciel ?"
    blanche  "Oh non ! Vite ! Fuyons !" with vpunch
    "Mais, à peine ai-je pu faire un pas, que Madame Arc-en-Ciel m'attrape."
    blanche "Ne me faites pas de mal. C'est… C'est que mon papa… Mon papa Noir… Il… Il est malade et je voulais lui montrer les couleurs pour le voir sourire."
    madame "Un instant… Papa ? Noir ? Il… Il est malade ?"
    madame "Tu… Tu serais donc son enfant ?"
    blanche "Oui, Madame Arc-en-Ciel…"
    madame "..."
    blanche "Je vous promets, Madame Arc-en-Ciel, je vous emprunte les boules juste pour un instant ! Après, je vous les rendrai !"
    blanche "Laissez-moi juste les montrer à mon papa !"
    madame "Amène-moi à ton père."
    blanche "Hein ?"
    madame "Amène-moi à ton père, tout de suite !"
    blanche "Euh… Oui ! Oui !"
    "Nous partons en direction du Quartier des Monochromes..."
    "Une fois entrés dans la maison, Madame Arc-en-Ciel découvre mon papa allongé sur le lit sans aucune force."
    "Le constat était sans appel. Mon papa allait bientôt s'éteindre."
    "En voyant la scène, Madame Arc-en-Ciel, qui était connue pour n'exprimer aucun sentiment, autre que la colère, s'effondre et commence à murmurer."
    madame "Mon vieil ami, Noir… Que s'est-il passé depuis tout ce temps…"
    madame "Est-ce le poids de la noirceur de ce monde qui t'a mis dans cet état-là ?"
    noir "Urgh… Urgh…"
    "Noir gémit."
    noir "Ciel… Est-ce toi ?"
    madame "Repose-toi… Garde tes forces."
    noir "Je suis désolé… Je ne mérite pas d'être ton partenaire de route. Je n'ai pas réussi à faire honneur à la tâche que tu m'as confiée."
    madame "Ne dis pas de sottises."
    noir "Urgh… Aaahh !!!"
    "Noir crie de douleur."
    blanche "Papa !"
    blanche "Papa ! Tu vas bien ?! Regarde, je t'ai amené les sept boules de Cristal ! Tu as vu leur couleur ?"
    noir "[player_name], tu…"
    "Noir se tait un instant puis sourit."
    noir "C'est très joli mon enfant. Mais, n'oublie pas de rendre ça à Mam- Madame Arc-en-Ciel."
    blanche "Oui !"
    "Je lui souris jusqu'aux oreilles."
    noir "Peux-tu me laisser un instant avec Madame Arc-en-Ciel ? J'aimerais discuter avec elle."
    noir "En attendant, tu pourrais me ramener des fleurs ?"
    blanche "Des fleurs ? Oh ! D'accord Papa !"
    "Je m'éloigne de lui et de Madame Arc-en-Ciel."
    "J'imagine qu'ils ont des choses à se dire..."
    "Quelque minutes plus tard..."
    madame "..."
    noir "..."
    noir "Ne lui en tiens pas rigueur. L'enfant est encore jeune…"
    madame "Montrez mes boules de cristal à quelqu'un qui ne peut voir… C'est insensé."
    "Madame Arc-en-Ciel pose sa main au niveau des yeux de Noir."
    noir "Huh ? Ciel ? Que fais-tu ?"
    madame "Ne discute pas."
    "Madame Arc-en-Ciel émet une lumière et concentre cette énergie sur Noir."
    "Noir reprend des couleurs."
    noir "Que… Que se passe-t-il ? Je sens comme une force revenir en moi."
    noir "Oh !"
    "Son bandeau tombe et révèle ses yeux… arc-en-ciel."
    "Noir se lève."
    noir "Je… Merci… Merci de m'avoir guéri."
    madame "..."
    noir "Je croyais… Je croyais que tu me haïssais… C'est pour cette raison que tu ne voulais plus me voir."
    madame "Tsss… Avec mes responsabilités au sein du royaume, j'ai très peu de temps pour moi ou pour qui que ce soit."
    madame "Je ne t'ai guéri que pour le bien de Couleurs."
    noir "Couleurs n'a pas besoin d'un moins que rien comme moi."
    madame "Mais, [player_name] a besoin de toi."
    noir "C'est vrai. Tu n'as pas tort..."
    "Noir sourit."
    madame "Et moi aussi…"
    noir "Hum ?"
    madame "Moi aussi, j'ai besoin de toi."
    noir "Oh ? Vraiment ?"
    madame "Tss… Ce n'est pas ce que tu crois. Je suis le soleil qui illumine ce monde et toi, tu es la lune qui le protège de l'obscurité..."
    madame "Il était évident qu'il fallait que je te sauve. C'est tout ce que je voulais dire."
    noir "Oh… Oui, je vois."
    madame "..."
    noir "..."
    "Madame Arc-en-Ciel et Noir se regardent les yeux dans les yeux."
    madame "Disons que pour Couleurs, je suis peut-être quelqu'un, mais sans toi, je ne suis rien."
    madame "C'est pour ça que je t'ai sauvé."
    noir "Pfft, hahaha."
    "Noir rit et prend dans ses bras Madame Arc-en-Ciel."
    madame "Hé ! Ne me touche p-"
    blanche "Papa ! Je t'ai ramené pleins de fleurs !"
    blanche "Oh ! Papa, tu es debout ! Trop bien ! Tu n'es plus malade !"
    blanche "Hein ? Mais pourquoi vous vous faites un câlin ? Moi aussi, j'en veux un !"
    "C'est ainsi que je pars en direction de Papa et Mam... Madame Arc-en-Ciel."
    #<illus de Noir et Blanche faisant un calin à Madame Arc-en-Ciel qui est rouge pivoine et embarassée>
