name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  RENPY_VERSION: ${{ vars.RENPY_VERSION || '8.3.6' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: project
    - name: "Prepare Ren'Py cache"
      id: cache-renpy
      uses: actions/cache@v3
      with:
        path: renpy
        key: ${{ runner.os }}-renpy-${{ env.RENPY_VERSION }}-core
    - name: "Install Ren'Py"
      uses: Ayowel/renpy-setup-action@v2
      if: steps.cache-renpy.outputs.cache-hit != 'true'
      with:
        action: install
        install_dir: renpy
        version: ${{ env.RENPY_VERSION }}
    - name: Lint
      run: ./renpy/renpy.sh project lint --error-code
