name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: project
    - name: "Prepare Ren'Py cache"
      id: cache-renpy
      uses: actions/cache@v3
      with:
        path: renpy
        key: ${{ runner.os }}-renpy
    - name: "Download Ren'Py"
      if: steps.cache-renpy.outputs.cache-hit != 'true'
      run: mkdir renpy && curl https://www.renpy.org/dl/8.0.2/renpy-8.0.2-sdk.tar.bz2 | tar -xjC renpy --strip-components 1
    - name: Lint
      run: ./renpy/renpy.sh project lint --error-code
